
spring.application.name=BooknBunk
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/bookNBunkDB
spring.datasource.username=springuser2025
spring.datasource.password=secretPassword
logging.level.root=info
logging.level.org.springframework.web=info
logging.level.org.hibernate=INFO

integrations.blacklist.url = "https://javabl.systementor.se/api/booknbunk/blacklist";
integrations.contract-customer.url = "https://javaintegration.systementor.se/customers";
integrations.event.host=128.140.81.47
integrations.event.username=djk47589hjkew789489hjf894
integrations.event.password=sfdjkl54278frhj7
integrations.event.queue-name=61da1eea-c67b-4707-9d2d-4ce48ecaf461
integrations.shipper.url = "https://javaintegration.systementor.se/shippers";
#integrations.mail =